# Generated by Django 6.0.4 on 2026-04-07 16:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='contactsubmission',
            options={'ordering': ['-created_at'], 'verbose_name': 'Aloqa xabari', 'verbose_name_plural': 'Aloqa xabarlari'},
        ),
        migrations.AlterModelOptions(
            name='profile',
            options={'verbose_name': 'Profil', 'verbose_name_plural': 'Profil'},
        ),
        migrations.AlterModelOptions(
            name='project',
            options={'ordering': ['-created_at'], 'verbose_name': 'Loyiha', 'verbose_name_plural': 'Loyihalar'},
        ),
        migrations.AlterModelOptions(
            name='skill',
            options={'ordering': ['category', 'name'], 'verbose_name': "Ko'nikma", 'verbose_name_plural': "Ko'nikmalar"},
        ),
        migrations.AlterField(
            model_name='contactsubmission',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Yaratilgan vaqt'),
        ),
        migrations.AlterField(
            model_name='contactsubmission',
            name='email',
            field=models.EmailField(max_length=254, verbose_name='Email'),
        ),
        migrations.AlterField(
            model_name='contactsubmission',
            name='message',
            field=models.TextField(verbose_name='Xabar'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='bio',
            field=models.TextField(blank=True, verbose_name='Bio'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='email',
            field=models.EmailField(max_length=254, verbose_name='Email'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='github',
            field=models.URLField(blank=True, verbose_name='GitHub'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Ism'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='phone',
            field=models.CharField(blank=True, max_length=20, verbose_name='Telefon'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='telegram',
            field=models.CharField(blank=True, max_length=50, verbose_name='Telegram'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='title',
            field=models.CharField(max_length=100, verbose_name='Lavozim'),
        ),
        migrations.AlterField(
            model_name='project',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Yaratilgan vaqt'),
        ),
        migrations.AlterField(
            model_name='project',
            name='description',
            field=models.TextField(verbose_name='Tavsif'),
        ),
        migrations.AlterField(
            model_name='project',
            name='github_url',
            field=models.URLField(blank=True, verbose_name='GitHub URL'),
        ),
        migrations.AlterField(
            model_name='project',
            name='image_url',
            field=models.URLField(blank=True, verbose_name='Rasm URL'),
        ),
        migrations.AlterField(
            model_name='project',
            name='live_url',
            field=models.URLField(blank=True, verbose_name='Jonli URL'),
        ),
        migrations.AlterField(
            model_name='project',
            name='tech_stack',
            field=models.CharField(max_length=500, verbose_name='Texnologiyalar'),
        ),
        migrations.AlterField(
            model_name='project',
            name='title',
            field=models.CharField(max_length=200, verbose_name='Sarlavha'),
        ),
        migrations.AlterField(
            model_name='skill',
            name='category',
            field=models.CharField(max_length=50, verbose_name='Kategoriya'),
        ),
        migrations.AlterField(
            model_name='skill',
            name='level',
            field=models.CharField(choices=[('beginner', "Boshlang'ich"), ('intermediate', "O'rta"), ('advanced', 'Yuqori')], default='intermediate', max_length=20, verbose_name='Daraja'),
        ),
        migrations.AlterField(
            model_name='skill',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Nomi'),
        ),
    ]
