# Generated by Django 6.0.4 on 2026-04-07 16:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_contactsubmission_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AboutMe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(verbose_name='Mazmun')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Yaratilgan vaqt')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Yangilangan vaqt')),
            ],
            options={
                'verbose_name': 'Men haqimda',
                'verbose_name_plural': 'Men haqimda',
                'db_table': 'about_me',
                'ordering': ['-updated_at'],
            },
        ),
        migrations.RemoveField(
            model_name='profile',
            name='bio',
        ),
    ]
