# Generated by Django 6.0.4 on 2026-04-07 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_aboutme_remove_profile_bio'),
    ]

    operations = [
        migrations.AddField(
            model_name='aboutme',
            name='email',
            field=models.EmailField(blank=True, max_length=254, verbose_name='Email'),
        ),
        migrations.AddField(
            model_name='aboutme',
            name='phone_number',
            field=models.CharField(blank=True, max_length=20, verbose_name='Telefon raqami'),
        ),
        migrations.AddField(
            model_name='aboutme',
            name='telegram',
            field=models.CharField(blank=True, max_length=100, verbose_name='Telegram'),
        ),
        migrations.AddField(
            model_name='aboutme',
            name='yearly_experience',
            field=models.IntegerField(default=0, verbose_name='Yillik tajriba'),
        ),
        migrations.AddField(
            model_name='aboutme',
            name='projects_completed',
            field=models.IntegerField(default=0, verbose_name='Tugallangan loyihalar'),
        ),
        migrations.AddField(
            model_name='aboutme',
            name='client_satisfaction',
            field=models.IntegerField(default=0, verbose_name='Mijozlar qanaqatligi (%)'),
        ),
        migrations.AddField(
            model_name='aboutme',
            name='technologies',
            field=models.TextField(blank=True, verbose_name='Texnologiyalar'),
        ),
    ]
