# Generated by Django 6.0.4 on 2026-04-07 17:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_add_aboutme_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='bot_username',
            field=models.CharField(blank=True, max_length=100, verbose_name='Bot username'),
        ),
        migrations.AddField(
            model_name='project',
            name='project_type',
            field=models.CharField(choices=[('web', 'Veb loyihasi'), ('bot', 'Telegram bot')], default='web', max_length=10, verbose_name='Loyiha turi'),
        ),
    ]
