# Generated by Django 5.2.14 on 2026-08-29 05:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_alter_aboutme_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='project_type',
            field=models.CharField(choices=[('web', 'Web project'), ('bot', 'Telegram bot'), ('mobile', 'Mobile app')], default='web', max_length=10, verbose_name='Project type'),
        ),
    ]
